### ISSUE TITLE
Web interface for SearchGPT

### ISSUE THREAD

**Issue by ministerinmarin** [perrys25/SearchGPT#1]
I have been enjoying this application for an hour and I though it would be fitting to run SearchGPT as a standalone web app where someone just places their API ID in one form, then write their prompts. Great for researchers and code noobs!

**Comment by psahnow** [comment]
Done! <https://searchgpt.perrysahnow.com> (Note it might not be up at the time of posting, I'm having some issues getting my websocket demo to run on the server hosting I have access to, mainly due to issues with chromedriver on a low performance VPS)
Source is at: <https://github.com/perrys25/searchgpt-demo>
